### ISSUE TITLE
More bullet problems

### ISSUE THREAD

**Issue by tdlowden** [18F/API-Usability-Testing#17]
Having major issues between the "preview" view and the actual view on the page. In the "schedule" section, the indented bullets appear indented and hollow in the preview, but appear in-line and filled-in on the real page. can't figure out why

**Comment by gbinal** [comment]
Sub-Bullets are fixed by using 2 extra spaces before the asterisk (for a total of 3 instead of 1), though I'm not sure why that is happening.  In the meantime, though, it should get us by.  

I've fixed the schedule section though don't know if others still need the same treatment
