### ISSUE TITLE
Agency checklist leads away from site

### ISSUE THREAD

**Issue by tdlowden** [18F/API-Usability-Testing#18]
in the kit, the agency checklist take us to a similar page under API-All-the-X. because it is built with the same template, it gets very confusing when the left nav all of the sudden changes to a bunch of different options.

**Comment by gbinal** [comment]
Great point.  I think I found a way to make links in markdown open in a new tab - `[text](url){:target="_blank"}`.  

It appears to be working for me and I'm adding it to any instances where something leads off site (including the meetup link), but if there are problems we may need to reopen this issue or file a new one.
