### ISSUE TITLE
Bold doesn't appear on final version, but does on preview

### ISSUE THREAD

**Issue by jdrubin** [18F/API-Usability-Testing#19]
Thanks!

**Comment by gbinal** [comment]
It's working for me.  Are you wrapping it in double asterisks?  E.g. `**text**`.  

A good habit with issues is to always include a link to where it's happening.  

The guide page is an example of bold working for me (screenshots below), but let me know if you can replicate it not working elsewhere.  

![screen shot 2014-05-16 at 10 31 01 am](https://cloud.githubusercontent.com/assets/633088/2998126/0ff6018e-dd07-11e3-9a51-e53ba2fe4be2.png)

![screen shot 2014-05-16 at 10 33 43 am](https://cloud.githubusercontent.com/assets/633088/2998133/19773958-dd07-11e3-8339-9c1adbfc27a6.png)

**Comment by jdrubin** [comment]
Weird... for two days it didn't work but now it looks OK. And I did the double *\* too. Yup, in the future I'll use a reference. Thanks!
