### ISSUE TITLE
Proposed changes to description of repo to make it clearer for users.

### ISSUE THREAD

**Issue by melodykramer** [18F/API-Usability-Testing#34]
Hey!

I'm doing a quick audit of all of 18F's GitHub repos to make sure that descriptions, README's, and issues are written as concisely and descriptively as they can be. This will help other organizations who would like to adapt our code as well as the public — who may be interested in adapting our code or contributing to our repos.

The current description of this repo is: A package for API Usability testing

Would it be possible to change it to: This repo contains an API usability testing toolkit which helps teams collect feedback from real or representative customers, and then act on the collected data.

I am also going to suggest some changes to your README.md through a pull request. I don't have access to change the description. 

Mel

**Comment by leahbannon** [comment]
I like this, but I think we need to make some changes for accuracy. How about "Unofficial website for the API Usability Testing project, which can help agencies collect real customer feedback to reduce errors, simplify work flow, and increase adoption of their APIs."

**Comment by melodykramer** [comment]
How about: "This repo contains the unofficial website for the API Usability Testing project, which can help agencies collect real customer feedback to reduce errors, simplify work flow, and increase adoption of their APIs."

**Comment by leahbannon** [comment]
I really think "this repo contains" is unnecessary and not in line with github common practice, so I would vote :-1: 

But we need @gbinal to weigh in on the language.

**Comment by melodykramer** [comment]
That's fine!

**Comment by webmaven** [comment]
@gbinal ping

**Comment by gbinal** [comment]
Belated but now done.
