### ISSUE TITLE
Contact email bounce back

### ISSUE THREAD

**Issue by awfrancisco** [18F/API-Usability-Testing#37]
Got an email to 18f@gsa.gov from someone who tried to use the contact email provided on this page and got a bounce back. Listed email is uxgov@gsa.gov. Needs to be updated. 

https://pages.18f.gov/API-Usability-Testing/pages/contact_us/

**Comment by gbinal** [comment]
Fixed.  Thanks.

**Comment by webmaven** [comment]
I think this issue can be closed.
